### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by phases78** [google-developer-training/android-basics-kotlin-unscramble-app#10]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
Task 7 "Populate Viewmodel" Steps 7 and 8: "Here is the completed getNextWord() method for your reference." 

**Describe the problem**
The codeblock(s) tries to update the public accessible val rather than private var: ++currentWordCount should be ++_currentWordCount ...it is correct in the walkthrough text but the codeblocks for reference are wrong.

Also it took me a while to debug why else I could not get to work, turns out my init block had to go after the getNextWord() function. Which maybe should have been obvious to me.. 

Thank you,

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@phases78 
We appreciate you reaching out to us.

1. Regarding the ++_currentWordCount issue. The change from `++currentWordCount` to `++_currentWordCount`  is done in the [Task number 11  Verify the ViewModel preserves data ](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=1#10) > Step 1. When you refractor this is done automatically. 

> In GameViewModel, right click on the variable currentWordCount, select Refactor > Rename... . Prefix the new name with an underscore, _currentWordCount.

Please check the step again, no need to update the documentation.

2. Updated the documentation to mention to add the `getNextWord()` above the `init` block. This should be published soon.

**Comment by phases78** [comment]
Thank you!
