### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by obinna-h-n** [google-developer-training/android-basics-kotlin-unscramble-app#100]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Task 4, Step 3

**Describe the problem**
This Step 3 says to "Change the backing field **currentWordCount** type to LiveData<String>...". 

The backing field name is wrong, its meant to be "Change the backing field **currentScrambledWord** type to...", because this is referring to the backing field for variable _currentScrambledWord.

**Steps to reproduce?**
1. Go to... [https://developer.android.com/codelabs/basic-android-kotlin-training-livedata#3](url)
2. Click on...Task 4 on the left menu, Read Step 1 and 2
3. See error...in Step 3

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by obinna-h-n** [comment]
Duplicate of #98

**Comment by jtavva** [comment]
Thank you for reaching out to us.
This should be fixed now.
