### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by DarkySuro** [google-developer-training/android-basics-kotlin-unscramble-app#103]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
the word "cat" is being shuffled to "cat" most of the time
I guess there is a problem with words consist of three or fewer letter-words

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![2021-07-26 (1)](https://user-images.githubusercontent.com/42028863/126935320-17bd30ea-85ef-4bff-abb7-c873809d2ff2.png)

**Comment by osuleymanova** [comment]
Hello @DarkySuro,

Thank you for reaching out and sharing your feedback. 
The issue is closed as won't fix, intended behavior.
