### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Bhasura88** [google-developer-training/android-basics-kotlin-unscramble-app#112]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6
**In which task and step of the codelab can this issue be found?**

**Describe the problem**

private fun getNextWord() {
   currentWord = allWordsList.random()
   val tempWord = currentWord.toCharArray()
   tempWord.shuffle()

   while (tempWord.toString().equals(currentWord, false)) {
       tempWord.shuffle()
   }
   if (**wordsList.**contains(currentWord)) {
       getNextWord()
   } else {
       _currentScrambledWord = String(tempWord)
       ++currentWordCount
       wordsList.add(currentWord)
   }
}
wordList is null and it throughs an exception for me :(
<img width="1296" alt="Screenshot 2021-08-27 at 01 08 29" src="https://user-images.githubusercontent.com/88440708/131025317-2dbbf845-c703-46ae-9e54-b7a7b5ef0a8a.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by caspervanpomeren** [comment]
Make sure to declare wordsList before you call getNextWord() in init, this solved it for me.

**Comment by amberream** [comment]
> Make sure to declare wordsList before you call getNextWord() in init, this solved it for me.

Just to add on to this, I found [this documentation](https://kotlinlang.org/docs/classes.html#constructors) which explains it a bit more.  In particular:

"During the initialization of an instance, the initializer blocks are executed in the same order as they appear in the class body, interleaved with the property initializers"

The order matters - the init block & variables get initialized in the order they appear.  So in this case, wordsList needs to be defined before calling the init block which in turn calls the method that accesses wordsList.
