### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by AtilanoParada** [google-developer-training/android-basics-kotlin-unscramble-app#119]
**URL of codelab**
https://developer.android.com/courses/pathways/android-basics-kotlin-unit-3-pathway-3

**In which task and step of the codelab can this issue be found?**
Training Viewmodel.
Step 2. Descripción general de la app de inicio.
Descarga el código de inicio.

**Describe the problem**
I tried to download the starter branch of the code given in github from the codelab but it only downloads the main branch.

**Steps to reproduce?**
1. Go to... https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/tree/starter
2. Click on... "Code" button, and then "Download Zip" option.
3. The zip is not the starter branch.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by SnoopyKim** [comment]
Use command
`git clone https://github.com/google-developer-training/android-basics-kotlin-unscramble-app.git --branch starter`

**Comment by AtilanoParada** [comment]
Thank you for the tip.
