### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by GregBradb** [google-developer-training/android-basics-kotlin-unscramble-app#12]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
Task 4. Add LiveData to the current scrambled word
Step 3

**Describe the problem**
Step 3 states:
Change the backing field **currentWordCount** type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps.

Instead of **currentWordCount** it should reference **currentScrambledWord**

**Steps to reproduce?**
1. Go to... the URL above
2. Click on...
3. See incorrect reference in step 3

**Versions**
_Android Studio version:_ 4.1.1.
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/8106705/104827887-d8386a00-5817-11eb-9224-67173fa3c7d0.png)

**Comment by jtavva** [comment]
@GregBradb 
Thank you so much for reporting this issue. This is fixed and will be published soon.
