### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by rossanafmenezes** [google-developer-training/android-basics-kotlin-unscramble-app#134]
**URL of codelab**

[Store Data in ViewModel](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#1)

**In which task and step of the codelab can this issue be found?**

2. Starter app overview

**Describe the problem**

The starter code is not really the starter code. It's the final code with all the changes already added. 

**Steps to reproduce?**
1 - Go to step 2 of the code lab [here](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#1)
2 - Follow the instructions to clone the GH repo for the starter code
3 - Note the app already has all the files and all the final code added

**Comment by JonathanBonnaud** [comment]
If you imported the project from Version Control, by default the branch is `main`, you can change it to `starter` at the bottom right of Android Studio.
