### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by psykoGabW** [google-developer-training/android-basics-kotlin-unscramble-app#14]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
code of getNextWord()

**Describe the problem**
It seems provided code has an issue...
while loop condition you indicate as reference : 
`   while (tempWord.toString().equals(currentWord, false)) {
       tempWord.shuffle()
   }`

With this code you try to compare tempWord memory reference with currentWord value

Shouldn't it be : 
`   while (String(tempWord).equals(currentWord, false)) {
       tempWord.shuffle()
   }`

With such change previous tempWord.shuffle() can be deleted by the way

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@psykoGabW 
Thank you for reaching out to us.


The reason it is done this way is after the first shuffle,  tempWord.shuffle(); The tempWord will be shuffled.  
Sometimes the shuffled word matches the original word, so we check it again and shuffle if necessary, inside the if block.  This if block is very rarely executed!
