### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by mkurom** [google-developer-training/android-basics-kotlin-unscramble-app#145]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Add a helper method

**Describe the problem**

```
fun nextWord(): Boolean {
    return if (currentWordCount < MAX_NO_OF_WORDS) {
        getNextWord()
        true
    } else false
}

```
There is no underscore in the currentWordCount of the if statement.

or These _currentWordCounts do not require an underscore.

```
if (wordsList.contains(currentWord)) {
    getNextWord()
} else {
    _currentScrambledWord = String(tempWord)
    ++_currentWordCount
    wordsList.add(currentWord)
}
```

```
/*
* Updates currentWord and currentScrambledWord with the next word.
*/
private fun getNextWord() {
   currentWord = allWordsList.random()
   val tempWord = currentWord.toCharArray()
   tempWord.shuffle()

   while (String(tempWord).equals(currentWord, false)) {
       tempWord.shuffle()
   }
   if (wordsList.contains(currentWord)) {
       getNextWord()
   } else {
       _currentScrambledWord = String(tempWord)
       ++_currentWordCount
       wordsList.add(currentWord)
   }
}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by HemantSachdeva** [comment]
Similar to #141
