### ISSUE TITLE
Android Basics: ViewModel.   Unscramble app starter code is messed up!

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-unscramble-app#149]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

starter code crashes as soon as it is ran.   I just downloaded.  I have not even done the 1st step.  You guys are getting sloppy.  How can I be prepared to take the exam when all the started apps are full of bugs or not opening at all?

screen shots included!

<img width="1440" alt="Screen Shot 2022-02-07 at 12 38 46 PM" src="https://user-images.githubusercontent.com/91148652/152851049-d7178b27-cd5b-490a-b9f8-3b282bc90906.png">
<img width="1440" alt="Screen Shot 2022-02-07 at 12 38 58 PM" src="https://user-images.githubusercontent.com/91148652/152851060-03e32ceb-c627-470a-aa9c-9d7fef009092.png">

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by EleoXDA** [comment]
I suggest you to redownload the zip.

In case it still fails, instead of screenshots, please copy paste the error log that shows in logcat (build output in your screenshot) so that we can find out why it gives error in your case (I checked and it didn't fail on my try)

**Comment by jh115424** [comment]
Ok, I will try that and let you know.

Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
