### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-unscramble-app#150]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata&authuser=1#11

**In which task and step of the codelab can this issue be found?**

it is noticed in the 3rd step.  I noticed it is not there at all!

**Describe the problem**

The GameViewModel is missing ENTIRELY in the starter code but is there in the code solution.

How can that be?     How can I do the project, if a part is missing?

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by EleoXDA** [comment]
In first steps (here: [https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#3](url) ) you are told to create the GameViewModel from scratch. That is why it is missing in starter code and present in main code.

**Comment by jh115424** [comment]
Ah!  ok....make  sense now.         thanks!


Jennifer Hodge

Internet Sales

414-586-5425

Russ Darrow Honda


[cid:2338ab7b-d825-4a0a-bf4c-b9ce4352fdb3]<https://your.tradeinvalet.com/tdhe0j>

________________________________
