### ISSUE TITLE
Android Basics: ViewModel. Word coun't doesn't update.

### ISSUE THREAD

**Issue by UtebayPi** [google-developer-training/android-basics-kotlin-unscramble-app#152]
**URL of codelab**
[URL](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#1)

**In which task and step of the codelab can this issue be found?**
12. step

**Describe the problem**

There is no code for updating word count in this app.

**Steps to reproduce?**
Just following the codelab will lead to the bug.

**Comment by ichwansh03** [comment]
you can update word count and score text inside onViewCreated to `score.text = getString(R.string.score, viewModel.score)` and `wordCount.text = getString(R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS)`
