### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by oppenheimerm** [google-developer-training/android-basics-kotlin-unscramble-app#163]
**URL of codelab**
[7. Populate ViewModel / point 7 ](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6)

**In which task and step of the codelab can this issue be found?**
7. Populate ViewModel/ step 7 method getNextWord()

**Describe the problem**
the example code as written in the tutorial in getNextWord(){
...
...
else {
       _currentScrambledWord = String(tempWord)
       ++_currentWordCount
       wordsList.add(currentWord)
   }
...
...
}

N variable declared(currentWordCount), or prior mention of this variable in the tutorial.  On further inspection I see from the project githhub it is declared as: private val _currentWordCount = MutableLiveData(0).  But it is not described in tutorial on that page.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by lufengdie** [comment]
Yes, you are right, the variant was declared in step 11, so It absolutely the wrong usage in step 7, so you can correct it by yourself and continue the rest part, you should not be stuck there by the little mistake they made.

<img width="767" alt="image" src="https://user-images.githubusercontent.com/3739366/163758312-0529ec57-19ca-46fe-831f-e79952125bf2.png">

Good luck and ahead.
