### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by martinprice20** [google-developer-training/android-basics-kotlin-unscramble-app#164]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
4. Add LiveData to the current scrambled word
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**Describe the problem**
After updating the _currentScrambledWord field to Mutable LiveData and attaching the observer in the GameFragment, the app will not compile, as _currentScrambledWord is not initialized

**Steps to reproduce?**
Using the Words Game App from the previous Android Basics Codelab (ViewModels)
Progress though the LiveData Codelab, completing steps 4 and 5. At the end of step 5 you should be able to run the app as before, but the app will not compile due to missing initialization of the _currentScrambledWord field

The step to initialize this field does not appear to be covered in step 4 or 5

**Versions**
_Android Studio version:_ Bumblebee
_API version of the emulator:_ API30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by seanyong-ncs** [comment]
I know this is thread is old. But I hope that this answer will help others who happen to be struggling with this same issue. 

The problem likely is that 

`private val _currentScrambledWord = MutableLiveData<String>()
    val currentScrambledWord: LiveData<String>
        get() = _currentScrambledWord`

is declared after the 

`init {
...
}`

block

Try moving the `_currentScrambledWord` declaration to before the init block and see if it will compile. It worked for me

**Comment by Florian-Martin** [comment]
Hello,

try this :

`
    private val _currentScrambledWord = MutableLiveData<String>()
    val currentScrambledWord: LiveData<String>
        get() = _currentScrambledWord
`

instead of :

`private lateinit var _currentScrambledWord: String
`

Your code should compile.

**Comment by adam10414** [comment]
@seanyong-ncs, holy shit thank you. This particular module seems to have a lot of issues with it! I'm finding myself chasing down bugs introduced by the lessons more than actually learning!

I be this also solves the other similar issue with wordsList! I ended up using the elvis operator on it to get around the null pointer exception.
