### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by Alahaz** [google-developer-training/android-basics-kotlin-unscramble-app#17]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
Task 4 step 4

**Describe the problem**
Typo in "Change the backing field **currentWordCount** type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps."

that should be "currentScrambledWord"

**Additional information**
the image that appear is 

![image](https://user-images.githubusercontent.com/33364922/105815490-8cd74600-5fe5-11eb-8064-ef65303c757a.png)

**Comment by jtavva** [comment]
@Alahaz 
Thank you so much for reporting this issue. This is fixed and will be published soon.
