### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by arjanga** [google-developer-training/android-basics-kotlin-unscramble-app#171]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**

In 7. Populate ViewModel, the step Get Next Word

**Describe the problem**

For some reason, I receive an error with the instantiated wordsList = mutableList<String>. Because the list was returning null, accessing the contains() function of the list was throwing an object reference error. To overcome this, I added the elvis operator to the wordsList Variable in its appropriate places and this fixed it.

**Steps to reproduce?**
1. Follow the steps through step 7
2. Click compile or debug
3. find the error
4. to fix it, implement my fix

**Versions**
_Android Studio version:_  2021.1
_API version of the emulator:_ API 32

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/82633830/166091288-6f19c1b8-7ae8-4bb2-94b3-4cbc711cb87d.png">

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/82633830/166091360-5ab47159-6ed5-49fe-aa5a-71b2701b31e9.png">

**Comment by adam10414** [comment]
Wow, thank you for this. +1 to this issue.

I was going mad trying to figure out what I did wrong, and I should have trusted my gut this whole time.
