### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by cdev75** [google-developer-training/android-basics-kotlin-unscramble-app#179]
I have written a lot of code I see in the https://developer.android.com/codelabs with plenty of errors. are they for the old version of android studio?
I don't understand. In the beginning, of https://developer.android.com/codelabs. they worked fine. after the dice project, the code I type in android studio doesn't work. what is the problem?

**Comment by android-dev-lxl** [comment]
@cdev75 
Thank you so much for reaching out to us.
Could you please give us more context.

Which codelab?
Which task?
What errors are you facing?
Could you please upload some screenshots?
