### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by ChibuFirst** [google-developer-training/android-basics-kotlin-unscramble-app#18]
**URL of codelab**
**https://developer.android.com/codelabs/basic-android-kotlin-training-livedata**

**In which task and step of the codelab can this issue be found?**
Task 8 and step 1 (Add data binding variables)

**Describe the problem**
**Just a typo**
**Mistake:** In `game_frament.xml`, inside the `<data>` tag ~~and~~ a child tag called `<variable>`...
**Correction:** In `game_frament.xml`, inside the `<data>` tag **add** a child tag called `<variable>` ...

**Additional information**
<img src="https://user-images.githubusercontent.com/52785343/106011984-48b67500-60bb-11eb-9a3f-0bfb3b8e9d46.PNG" alt="Typo Screenshot" width="500">

**Comment by jtavva** [comment]
@ChibuFirst 
Thank you so much for reporting this issue. This is fixed and will be published soon.
