### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by RCrozier** [google-developer-training/android-basics-kotlin-unscramble-app#180]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12

**In which task and step of the codelab can this issue be found?**
13

**Describe the problem**
Solution code seems incorrect as all progress made to the code is wiped out and now none of the newly implemented functions work. Before replacing my code with the 'solution' code, my app was working as expected. After replacing all code with the solution code, it seems as though it's back to not functioning correctly. Code will compile and run on the device, but it's as it was at the start of the code lab without any functionality working at all.

**Steps to reproduce?**
1. Perform steps from the code lab
2. Compile and test app, it's working as per the code lab
3. Replace all code in the project from the 'solutions' code
4. Application compiles and runs, but no buttons work, word scrambling doesn't work etc.

**Versions**
_Android Studio version:_ 2021.2.1
_API version of the emulator:_ 32

**Additional information**

![image](https://user-images.githubusercontent.com/8973349/171046969-bc107feb-a4c7-48d7-b961-fd88cc365bf0.png)

**Comment by android-dev-lxl** [comment]
@RCrozier 
Thank you for reaching out to us.
Have you tried playing the game?
