### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by ibnfarooq26** [google-developer-training/android-basics-kotlin-unscramble-app#181]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12)**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12

**In which task and step of the codelab can this issue be found?**
13.Solutions

**Describe the problem**

1) In the Solution Code,   for `GameFragment.kt`,  
```
binding.score.text = getString(R.string.score, 0)
        binding.wordCount.text = getString(
            R.string.word_count, 0, MAX_NO_OF_WORDS)
```
The value 0 for both `score` and `word` is hardcoded. It should be taken from `GameViewModel.kt` instead.  So the correction is
```
  binding.score.text = getString(R.string.score, viewModel.score)
        binding.wordCount.text = getString(
                R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS)
```

2) The function `onSubmitWord()`  does not have the code to update the UI `score` and  `wordcount`. So the following code to be included there:
  ```
binding.score.text = getString(R.string.score, viewModel.score)
        binding.wordCount.text = getString(
            R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS)
```
3) The function `getNextScrambledWord()` has never been used anywhere in the code.
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Alikrema** [comment]
A really good catch! I spent some time wondering if I missed something and ended up changing the code myself. Glad someone put that in the issues!

**Comment by android-dev-lxl** [comment]
@Alikrema 
Thank you for replying to the issue. That is the exact answer.
@ibnfarooq26 
Thank you for reaching out to us. Hope this helps.
