### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by HemashreeDalvi** [google-developer-training/android-basics-kotlin-unscramble-app#184]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#1

**In which task and step of the codelab can this issue be found?**
Step 2 : Starter app overview

**Describe the problem**
Starter Code URL: https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/tree/starter

The project in github url is different form codelab . 

**Steps to reproduce?**
1. Go to... step 2 (Starter app overview)
2. Click on... github project link
3. See error... downlod zip and check

**Versions**
_Android Studio version:_ chipmunk
_API version of the emulator:_  NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@HemashreeDalvi 
Thank you for reaching out to us.

Could you please tell us what exactly is the error.

**Comment by HemashreeDalvi** [comment]
When I was working on it that time I found the starter project in below mention github project link is having different from codelab.

Code URL: https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/tree/starter
