### ISSUE TITLE
Android Basics: ViewModel: Instructions out of order.

### ISSUE THREAD

**Issue by virtuallyLuna** [google-developer-training/android-basics-kotlin-unscramble-app#186]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Codelab 2: Store data in ViewModel
Task 7: Populate ViewModel
"Get next word" section, step 7

**Describe the problem**
The if-else block in getNextWord() uses _currentWordCount, which is a private var requiring a backing property, which is not done until Task 11. The problem is simple and easy to fix, but it does make it confusing for students who are strictly following the given steps and may not realize the problem.

**Steps to reproduce?**
Just follow the instructions exactly as-is in the codelab.

**Versions**
_Android Studio version:_  Android Studio Chipmunk | 2021.2.1 Patch 1
Build #AI-212.5712.43.2112.8609683
_API version of the emulator:_  API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/108907023/177917533-3545f626-bdbd-424d-b98b-6002157892df.png)

![correctTheError](https://user-images.githubusercontent.com/108907023/177918698-e5b0a786-5d54-44c6-b3ba-b9050981d860.png)

**Comment by android-dev-lxl** [comment]
@virtuallyLuna 
Thank for the fix and thank you for reaching out to us.
Yes that is the right fix.
This is fixed and will be published soon.
