### ISSUE TITLE
Android Basics: LiveData - Hyperlink to deprecated docs

### ISSUE THREAD

**Issue by xirayah** [google-developer-training/android-basics-kotlin-unscramble-app#187]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#0)**

**Step 1**

**The first hyperlink for LiveData redirects to deprecated version of LiveData in the docs**

**Steps to reproduce?**
1. Go to step 1
2. Click on first LiveData hyperlink

**Comment by android-dev-lxl** [comment]
@xirayah 
Thank you for reaching out to us!

Fixed and to be published.
