### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by akabuezendudiha** [google-developer-training/android-basics-kotlin-unscramble-app#188]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12

**In which task and step of the codelab can this issue be found?**
The issue can be found in Task 12, the final solution code of the Android Basics: ViewModel Codelab.

**Describe the problem**
The final solution code does not update **score** [SCORE: 0] and **wordCount** [0 of 10 words] from the viewModel at all. 
The only assignment for [binding.score] and [binding.wordCount] is in the [onViewCreated] fun and should be moved into the [updateNextWordOnScreen] function and values set from the [viewModel.score] and [viewModel.currentWordCount] respectively.

**Steps to reproduce?**
1. Go to the [onViewCreated] function in the solution code
2. Below the [updateNextWordOnScreen] function call, the [binding.score] and [binding.wordCount] are initialised with static value 0.
3. This causes buggy behavior as [**binding.score**] and [**binding.wordCount**] are never updated with [**viewModel.score**] and [**viewModel.currentWordCount**] respectively.

**Versions**
_Android Studio version: Android Studio Chipmunk | 2021.2.1 Patch 1
_API version of the emulator: 29_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Code Issue**
![snap-01](https://user-images.githubusercontent.com/21034314/184524930-d38da80f-e9a9-4dc9-95fe-4fb70ba58522.GIF)

**Possible Solution**
![snap-02](https://user-images.githubusercontent.com/21034314/184525098-0a30c3ac-d036-424f-9a3a-21456fabd914.GIF)

**Comment by android-dev-lxl** [comment]
@akabuezendudiha 
Thank you for reaching out to us.
This is intentional behavior and is also mentioned in the codelab. 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/24260141/213088739-f85369aa-80ec-4d06-bf7c-6c9dd10d1dc7.png">

https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#11
