### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by cmcoffeedev** [google-developer-training/android-basics-kotlin-unscramble-app#191]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
Step 7
Step 13

**Describe the problem**
The first issue is a small typo. Step 5 tells you to copy over currentWordCount to the ViewModel. Step 7 uses _currentWordCount in the examples. We don't create a backing property for currentWordCount until step 11.

The second issue is small as well. It doesn't mention using viewModel.score and viewModel.currentWordCount in onViewCreated. It is not updated in the solution step as well (step 13).

**Steps to reproduce?**
1. Go to... 
3. Click on...
4. See error...

**Versions**
_Android Studio version:_ 
Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 1920M
Cores: 8

_API version of the emulator:_ 
30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by lixoten** [comment]
I see the same error/problem.... Do they want us to add a backing property to currentWordCount as it was done to currentScrambledWord

**Comment by cmcoffeedev** [comment]
> I see the same error/problem.... Do they want us to add a backing property to currentWordCount as it was done to currentScrambledWord

I believe so. They have a backing property for currentWordCount in step 11.
[https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#10](Step 11)

**Comment by android-dev-lxl** [comment]
@cmcoffeedev 
Thank you for reaching out to us.

**First issue: backing property for currentWordCount**
Fixed, to be published!

**Second issue: UI is not updated**

This is intentional behavior and is also mentioned in the codelab. 

<img width="734" alt="image" src="https://user-images.githubusercontent.com/24260141/213088739-f85369aa-80ec-4d06-bf7c-6c9dd10d1dc7.png">

https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#11
