### ISSUE TITLE
Android Basics: ViewModel GameFragment log TAG

### ISSUE THREAD

**Issue by EssiJunior** [google-developer-training/android-basics-kotlin-unscramble-app#192]
URL - https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#5

Task 6 - Lifecycle of a ViewModel

In steps 1 and 3, we are suppose to log a message in GameViewModel using "Log.d()". The tag present is "GameFragment" instead of "GameViewModel"

**Comment by android-dev-lxl** [comment]
@EssiJunior 
Thank you for reaching out to us. 
Yes, the TAG is GameFragment. The reason for using the same tag is that it would be easier to filter the Logcat messages with one filter.

**Comment by EssiJunior** [comment]
> @EssiJunior 
> Thank you for reaching out to us. 
> Yes, the TAG is GameFragment. The reason for using the same tag is that it would be easier to filter the Logcat messages with one filter. 

Okay, thanks for the response.

**Comment by EssiJunior** [comment]
@android-dev-lxl 

Okay! I understand. 
Thanks for the response.
