### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Pabloku** [google-developer-training/android-basics-kotlin-unscramble-app#193]
**[URL of codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#5)**

**In which task and step of the codelab can this issue be found?**
Step 8 of Task 6 (The lifecycle of a ViewModel)

**Describe the problem**
The task says that I should be seeing a log when the ViewModel onCleared and the Fragment onDetach methods are called but from Android 12 and higher, this log will not appear cause from Android 12, root activities are no longer finished on the Back press.

**Steps to reproduce?**
1. Implement what codelab says until task 6 and step 8
2. Run the app in a device with Android 12 or higher
3. You won't see the supposed log about GameViewModel destroyed! and GameFragment destroyed!

**Versions**
_Android Studio version:_ Any
_API version of the emulator: API 31 or higher

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by dsingh06** [comment]
+1

**Comment by za73094** [comment]
+1
