### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by dsingh06** [google-developer-training/android-basics-kotlin-unscramble-app#195]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fhl%3Den%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata&hl=en#3

**In which task and step of the codelab can this issue be found?**
Changing game view model

**Describe the problem**
Starter code does not have this class

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@dsingh06 
Thank you for reaching out to us.
As mentioned in the codelab, please add the code from the previous codelab.
<img width="703" alt="image" src="https://user-images.githubusercontent.com/24260141/213085275-74cd456c-0181-476a-be49-d42ca87f4e37.png">

Solution code for the previous codelab ( [Store data in ViewModel](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel)) 
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#12
