### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by BMteacher** [google-developer-training/android-basics-kotlin-unscramble-app#196]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
In 7 part between 5,6 steps

**Describe the problem**
> whereas a List has add() and remove() functions, so that it can increase and decrease in size.
In Kotlin List doesn't have such methods, suggestion is to replace with MutableList

**Steps to reproduce?**
Click 7 part
Scroll to 5 step

**Versions**
site version

**Additional information**
<img width="1519" alt="image" src="https://user-images.githubusercontent.com/114387232/197373387-69cc39fa-513a-4b4a-9c00-faccc959bb40.png">

**Comment by android-dev-lxl** [comment]
Fixed to be published

**Comment by osuleymanova** [comment]
Hello @BMteacher,

Thank you for reaching out to us and reporting this typo. It's fixed:

![Screenshot 2023-01-17 at 4 45 29 PM](https://user-images.githubusercontent.com/86437155/213053420-2a01615e-eb3f-4216-9c2a-52239186db2a.png)
