### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by M-G-Olsen** [google-developer-training/android-basics-kotlin-unscramble-app#198]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

In module 7, _currentWordCount is used even if this is not implemented until module 11.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
Fixed to be published!

**Comment by osuleymanova** [comment]
Hello @M-G-Olsen,

Thank you for reaching to us and sharing your concern. The steps and code snippets are updated:


![Screenshot 2023-01-17 at 4 51 20 PM](https://user-images.githubusercontent.com/86437155/213053972-f9fe63b0-93fb-4980-bbf8-a0813e35a230.png)
