### ISSUE TITLE
Lambda expession in observer currentWordCount

### ISSUE THREAD

**Issue by DemisChan** [google-developer-training/android-basics-kotlin-unscramble-app#199]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#8

**In which task and step of the codelab can this issue be found?**
When setting the observers in the GameFragment

**Describe the problem**
There is no problem I just wanted to know what is the purpose of the third parameter in the getString method?

```kotlin
viewModel.currentWordCount.observe(viewLifecycleOwner,
   { newWordCount ->
       binding.wordCount.text =
           getString(R.string.word_count, newWordCount, MAX_NO_OF_WORDS)
   })
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by IanRiley237** [comment]
The `word_count` string resource has two arguments, the `%d`'s on either side of the word `of`.
```
<string name="word_count">%d of %d words</string>
```
Assuming `newWordCount` is 3, and `MAX_NO_OF_WORDS` is 10, then the string would become: `3 of 10 words`.
I hope that helps.

**Comment by android-dev-lxl** [comment]
@DemisChan Thank you for reaching out to us!
@IanRiley237 Thank you replying, that is exactly the reason.
