### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by alzifoztran** [google-developer-training/android-basics-kotlin-unscramble-app#20]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
Task 4 "Add LiveData to the current scrambled word",  step 3

**Describe the problem**

step 3 is typo,

"Change the backing field **currentWordCount** type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps."

it should be **currentScrambledWord**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@alzifoztran 
Thank you so much for reporting this issue. This is fixed and will be published soon.
