### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by evolquez** [google-developer-training/android-basics-kotlin-unscramble-app#202]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#11

**In which task and step of the codelab can this issue be found?**
Step 12

**Describe the problem**
The textview that display the score on the screen is never updated. The score text is only changed on onViewCreated method from the fragment.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot_1671851965](https://user-images.githubusercontent.com/8124733/209419375-47c44951-b2f5-4c64-a645-b6fa437b0cee.png)

**Comment by evolquez** [comment]
Maybe this could be a temp solucion for this codelab:
```
 private fun onSubmitWord() {
        val playerWord = binding.textInputEditText.text.toString()
        if(viewModel.isUserWordCorrect(playerWord)) {
            setErrorTextField(false)
            binding.score.text = getString(R.string.score, viewModel.score) // **Adding this line**
            if(viewModel.nextWord()){
                updateNextWordOnScreen()
            }else{
                showFinalScoreDialog()
            }
        }else {
            setErrorTextField(true)
        }
    }
```

**Comment by android-dev-lxl** [comment]
@evolquez 
Yes that is right!
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#10

<img width="860" alt="image" src="https://user-images.githubusercontent.com/24260141/213044996-1a1c7824-74da-4ce3-b04d-c37c500e1bd0.png">
