### ISSUE TITLE
Android Basics: viewModels

### ISSUE THREAD

**Issue by moisedk** [google-developer-training/android-basics-kotlin-unscramble-app#203]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#5

**In which task and step of the codelab can this issue be found?**
Task 6 Step 1 and 3

**Describe the problem**
Log TAGs seems incorrect. GameFragment appears everywhere even when login information about GameViewModel

**Steps to reproduce?**
1. Go to... the URL above
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ N/A
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by android-dev-lxl** [comment]
@moisedk 
Could you please give us some more context, like what exactly is incorrect? 
May be some logs, screenshots and filters you are using will help.

**Comment by moisedk** [comment]
@android-dev-lxl  It might be an error of minor importance, actually.
Please see the screenshot below. "GameFragment" in the log message should be "GameViewModel"
![Screenshot from 2023-01-17 20-13-47](https://user-images.githubusercontent.com/56738242/213056973-c9b2719c-bba5-45e5-b388-f51f99f10cee.png)
