### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by ges1908** [google-developer-training/android-basics-kotlin-unscramble-app#204]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
Final Test
**Describe the problem**

1.  Design mode  of the fragments is not visible
2.  score and word count views aren't updated while playing
3. user input edit text is not set to null when skipping a word

**Steps to reproduce?**
1. run app with solution code
**Versions**
_Android Studio version:_ Android Studio Dolphin | 2021.3.1 Patch 1
Build #AI-213.7172.25.2113.9123335, built on September 30, 2022

_API version of the emulator:_ 31.3.14

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
Hello @ges1908,

Please provide the codelab URL.

**Comment by android-dev-lxl** [comment]
@ges1908 
Thank you for reaching out to us!

> 1. Design mode of the fragments is not visible
Please send us a screenshot!

> 2. score and word count views aren't updated while playing
Yes that is right!
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#10

<img width="860" alt="image" src="https://user-images.githubusercontent.com/24260141/213044996-1a1c7824-74da-4ce3-b04d-c37c500e1bd0.png">

> 3. user input edit text is not set to null when skipping a word
This is intended behavior. Please feel free to implement this task as a challenge task. Keep us posted on how it went.
