### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by wos-dv** [google-developer-training/android-basics-kotlin-unscramble-app#21]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Step 6

**Describe the problem**
In this code fragment:

```
while (tempWord.toString().equals(currentWord, false)) {
    tempWord.shuffle()
}
```

tempWord.toString() does not actually give the String represented by the CharArray, but the String of the address of the char array (or something like that). 

The solution is to use String() constructor with the CharArray as argument.
```
while (String(tempWord).equals(currentWord, false)) {
    tempWord.shuffle()
}
```

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_ 29

**Comment by jtavva** [comment]
@wos-dv 
Thank you so much for reporting this issue. This is fixed and will be published soon.
