### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by mishraspecific** [google-developer-training/android-basics-kotlin-unscramble-app#220]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
In slide 7([7. Populate ViewModel]) of step 8 
**Describe the problem**
in the getNextWord() function, the currentWordCount is being incremented instead of _currentWordCount. This is causing an error because currentWordCount is a val variable.
**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
<img width="1003" alt="Screenshot 2023-03-16 at 12 20 57 AM" src="https://user-images.githubusercontent.com/661421/225374325-f78df3d1-1eba-48fb-a426-5b4521c9dd74.png">

_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by RobertWonchFRCC** [comment]
Nobody at android cares... at all.
