### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Hujumajujubon** [google-developer-training/android-basics-kotlin-unscramble-app#24]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Task 7 - Populate ViewModel
Step 6 

**Describe the problem**
The guide instructs users to write the following conditional to ensure the char array was indeed shuffled. 

while (tempWord.toString().equals(currentWord, false)) {
    tempWord.shuffle()
}

However, the conditional will always return false even when the expected behavior would be true. This is because tempWord.toString() returns a reference and not the concatenated characters. A simple solution to get the actual expected behavior is to use contentEquals as shown below. 

while (tempWord contentEquals currentWord.toCharArray()){
     tempWord.shuffle()
}

**Steps to reproduce?**
Omit the shuffle() call before the while loop. (essentially forcing the loop to execute at least once)

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Hujumajujubon 
Thank you so much for reporting this issue. This is fixed and will be published soon.
