### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by Ninjacodec** [google-developer-training/android-basics-kotlin-unscramble-app#25]
**https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3**

**4. Add LiveData to the current scrambled word**

**Change the backing field currentWordCount type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps.**

**Steps to reproduce?**
1. https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3
2. 4. Add LiveData to the current scrambled word
3. Change the backing field currentWordCount type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps. 

**Versions**
_Android Studio version:_ Android Studio 4.1.2
_API version of the emulator:_  28
![Capture123](https://user-images.githubusercontent.com/41590739/108432139-f3eac200-7254-11eb-84bb-ce55832b71ab.PNG)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Ninjacodec** [comment]
Should be: Change the backing field currentScrambledWord type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps.

**Comment by jtavva** [comment]
Same as #17
Thank you so much for reporting this issue. This is fixed and will be published soon.
