### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by KAPLANDROID** [google-developer-training/android-basics-kotlin-unscramble-app#28]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
Task 7 Populate ViewModel -> Get next word.-> step 7 also step 8

**Describe the problem**
In the sample code there is an attempt to increase the value of final "val" property.
"++currentWordCount" which should be "++_currentWordCount"

**Steps to reproduce?**
1. go to getNextWord() method
2. Paste the sample code and Run
3. Compile time error "Val cannot be reassigned"

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by nokyslash** [comment]
In the sample code there is an attempt to increase the value of final "val" property.
"++currentWordCount" which should be "++_currentWordCount"

OR :
_currentWordCount++

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
