### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by nokyslash** [google-developer-training/android-basics-kotlin-unscramble-app#29]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#4

**In which task and step of the codelab can this issue be found?**
Task 2, Step 5

**Describe the problem**
the example code throws the error in Android Studio

**Steps to reproduce?**
1. Go to...Task 2, step 5, Add backing property to currentScrambledWord
2. Click on...
3. See error...private fun updateNextWordOnScreen() {
   binding.textViewUnscrambledWord.text = **viewModel**.currentScrambledWord
}
when it should be:
private fun updateNextWordOnScreen() {
   binding.textViewUnscrambledWord.text = **gameViewModel**.currentScrambledWord

since the instance declared above is precisely of GameViewModel and not of ViewModel

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_ Physical Device

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Sin título](https://user-images.githubusercontent.com/46078334/110271733-9796da80-7f96-11eb-8f64-a6da58920c87.png)

**Comment by jtavva** [comment]
Thank you for reaching out to us.
The instance name in the codelab is `viewModel` not `gameViewModel`.
![image](https://user-images.githubusercontent.com/24260141/115433419-6841d300-a1bc-11eb-8bd4-2256b3018994.png)

You are facing this issue because you might have refactored in your code. Please check again from your end.
No need to update codelab content.
