### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by egoldbloom** [google-developer-training/android-basics-kotlin-unscramble-app#30]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
This issue is first seen in task 7 step 6.  It can also be seen anywhere that the getNextWord() function is detailed

**Describe the problem**

The while loop of the getNextWord method uses a toString() on a character array.  This appears to return a string that contains the starting address of the CharArray.  I believe that the proper way to convert a CharArray to a String is to wrap the array in a String() function.

As it is written, the while loop will never be entered since the String and the address of the CharArray will never be equal.

Here is the original code:

    /*
    * Updates currentWord and currentScrambledWord with the next word.
    */
    private fun getNextWord() {
        currentWord = allWordsList.random()
        val tempWord = currentWord.toCharArray()
        tempWord.shuffle()

        while (tempWord.toString().equals(currentWord, false)) {
            tempWord.shuffle()
        }
        if (wordsList.contains(currentWord)) {
            getNextWord()
        } else {
            _currentScrambledWord = String(tempWord)
            ++_currentWordCount
            wordsList.add(currentWord)
        }
    }

Here is the modified code:

    /*
    * Updates currentWord and currentScrambledWord with the next word.
    */
    private fun getNextWord() {
        currentWord = allWordsList.random()
        val tempWord = currentWord.toCharArray()
        // tempWord.shuffle()

        while (String(tempWord).equals(currentWord, false)) {
            tempWord.shuffle()
        }
        if (wordsList.contains(currentWord)) {
            getNextWord()
        } else {
            _currentScrambledWord = String(tempWord)
            ++_currentWordCount
            wordsList.add(currentWord)
        }
    }

**Steps to reproduce?**
1. Comment out the first tempWord.shuffle().  This should force the while condition to be true on the first iteration
2. Put a log statement inside the while loop.
3. Run the app.  You will see that the words in the app are never shuffled and that the log message doesn't appear

**Versions**
_Android Studio version:_ 4.1.2
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
