### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by AnotherPianist** [google-developer-training/android-basics-kotlin-unscramble-app#31]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
4. Add LiveData to the current scrambled word

**Describe the problem**
In the 3rd point of the explanation it says we should modify `currentWoredCount`, but the variable that should be modified is `currentScrambledWord`. It's correct in the code snippet, but not in the explanation paragraph.

**Steps to reproduce?**
1. Go to the 4th screen of the Use LiveData with ViewModel codelab, Add LiveData to current scrambled word
3. See error on the paragraph that starts with 3. Change the backing field...

**Versions**
It's on the course website, not in the code itself.

**Additional information**
![image](https://user-images.githubusercontent.com/32588448/111053266-209f8d00-8441-11eb-99e7-f349633edae4.png)

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
