### ISSUE TITLE
Android Basics

### ISSUE THREAD

**Issue by enikebraimoh** [google-developer-training/android-basics-kotlin-unscramble-app#32]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
the starter code is containing the solutions,,,, please can you provide an empty starter code so i could use to follow up the course

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by AnotherPianist** [comment]
You can clone the GitHub repository and checkout to the `starter` branch, there it's the starter code you need to complete the codelab.
But yes, they need to change that.

**Comment by enikebraimoh** [comment]
I cloned the starter branch, but it still has the solution code.

Please is there a way you can provide the starter code?? The starter branch
already has the solution..

**Comment by jtavva** [comment]
Thank you for reaching out to us.
Before downloading make sure branch is selected correctly as `starter`.

![image](https://user-images.githubusercontent.com/24260141/115434795-f4082f00-a1bd-11eb-8bf0-96d1dea38ff1.png)

Alternatively please download from the following link:

https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/archive/refs/heads/starter.zip
