### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by tkyeung357** [google-developer-training/android-basics-kotlin-unscramble-app#33]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
7. Populate ViewModel
13. Solution code

**Describe the problem**
I got a shuffled word "you" which is equal to original word, problem solved by change to `String(tempWord).equals(currentWord, false)`

```
while (tempWord.toString().equals(currentWord, false)) {
    tempWord.shuffle()
}
```

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
