### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by NalinMeher** [google-developer-training/android-basics-kotlin-unscramble-app#34]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=6&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D6%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
7. Populate ViewModel >> Get next word 

**Describe the problem**

```
while (tempWord.toString().equals(currentWord, false)) {
    tempWord.shuffle()
}

```
needs to change to

```
while (String(tempWord).equals(currentWord, false)) {
      tempWord.shuffle()
}
```

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
