### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by ente-ente** [google-developer-training/android-basics-kotlin-unscramble-app#42]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**

Get next word 6.
**Describe the problem**

tempWord.toString() gives the address which is never the same as currentWord, therefore the word is never being scrambled in this version. (ext.kotlin_version = "1.4.32")

Solution: use tempWord.joinToString(separator = "")

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
![image](https://user-images.githubusercontent.com/35533630/113478812-894fb780-948b-11eb-8c7a-24f10dc1196f.png)
![image](https://user-images.githubusercontent.com/35533630/113478822-979dd380-948b-11eb-8c0d-6a49550d7c55.png)

**Comment by jtavva** [comment]
@ente-ente 
Thank you for reaching out to us.
Yes this is a known issue, the correct code is as follows:

```
while (String(tempWord).equals(currentWord, false)) {
    tempWord.shuffle()
}
```

Thank you so much for reporting this issue. This is fixed and will be published soon.
