### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Giovanni0412** [google-developer-training/android-basics-kotlin-unscramble-app#43]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Populate ViewModel

**Describe the problem**

Until this step of the codelap, a backup property of the currentWordCount variable has not been requested, which variable is used in the code of this task

**Steps to reproduce?**
1. Go to...

 private var _currentWordCount = 0
        var currentWordCount:Int = 0
        get() = _currentWordCount

2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Giovanni0412 
Thank you for reaching out to us.
They are data variables in the `GameViewModel.kt.`. Which are added in Task 5. Move data to the ViewModel.

![image](https://user-images.githubusercontent.com/24260141/115442224-9debb980-a1c6-11eb-8b6e-793ff0aa9686.png)

Let us know if that answers your question.

**Comment by jtavva** [comment]
@Giovanni0412 
It's been more than 2 months since we've heard from you, so we are going to close this ticket. You can always reopen this ticket or raise a new one if you need any further assistance.
