### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by dyopet** [google-developer-training/android-basics-kotlin-unscramble-app#46]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=5&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D5%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Store data in ViewModel

**Describe the problem**
i am stuck in the private fun getNextWord in GameViewModel.kt where the code is supposed to create an empty mutable list:
private var wordsList: MutableList<String> = mutableListOf()       ---> this line creates wordslist as null.
if (wordsList.contains(currentWord)) {        ---> this line produces an error: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.add(java.lang.Object)' on a null object reference

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/82293138/114287050-80b43e00-9a96-11eb-9614-c96c3b006d38.png)

**Comment by dyopet** [comment]
I made it work by removing 'private var wordsList: MutableList<String> = mutableListOf()' from GameViewModel.kt and putting 'val wordsList: MutableList<String> = mutableListOf()' inside ListOfWords.kt 

my concern with this correcton is: will there be any issue with it? like a leak or something?

![image](https://user-images.githubusercontent.com/82293138/114287378-ec97a600-9a98-11eb-9432-2a40e89bf41f.png)

**Comment by jtavva** [comment]
@dyopet 
Thank you for reaching out to us.
This is same as #39 
Could you please check the suggested solution and let us know if that works. 
If you still face issues, please send in your code.

**Comment by dyopet** [comment]
yes it worked.

thanks a lot.
