### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by TeeRenJing** [google-developer-training/android-basics-kotlin-unscramble-app#49]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#12

**In which task and step of the codelab can this issue be found?**
Solution code doesn't seem to be working.

**Describe the problem**
Solution code doesn't seem to be working after copy and pasting the provided code into GameFragment.kt and GameViewModel.kt 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  4.1.3
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@TeeRenJing 
We appreciate you bringing this issue to our attention.
Could you please provide more details of the error you are encountering so they may help you resolve the issue.
1. Copy paste the error
2. Add corresponding screenshot.
