### ISSUE TITLE
The starter code isn't actually THE starter code!

### ISSUE THREAD

**Issue by imahmwd14** [google-developer-training/android-basics-kotlin-unscramble-app#5]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
The problem is in the GitHub repo.

**Describe the problem**
As written in the title, the starter code in this repo isn't actually the starter code, it's the solution code!

**Comment by jtavva** [comment]
@imahmwd14 
Thank you for reaching out to us.
Pull request: https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/pull/6
This should be fixed now.
