### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by 2dnas** [google-developer-training/android-basics-kotlin-unscramble-app#50]
**https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3**

**4. Add LiveData to the current scrambled word **

**step 3 there are statement "Change the backing field currentWordCount type to LiveData<String>, because it is immutable" 
and there should be currentScrambledWord instead of currentWordCount **

**Steps to reproduce?**
1. Go to the link and task 4...
2. scroll down a bit at step 3...
3. and there are wrong variable name in explanation
![issue](https://user-images.githubusercontent.com/44274932/115120423-7b874f80-9fbe-11eb-934d-f17a7c1b112a.PNG)
...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
Thank you so much for reporting this issue. This is fixed and will be published soon.
