### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by mshoaib-murtaza** [google-developer-training/android-basics-kotlin-unscramble-app#52]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel#7

**In which task and step of the codelab can this issue be found?**
At this line 
currentWord = allWordsList.random()
inside getNextWord() method

**Describe the problem**
when i run the app, following error occurs
FATAL EXCEPTION: main
    Process: com.example.android.unscramble, PID: 9422
    java.util.NoSuchElementException: Collection is empty.
        at kotlin.collections.CollectionsKt___CollectionsKt.random(_Collections.kt:528)
        at com.example.android.unscramble.ui.game.GameViewModel.getNextWord(GameViewModel.kt:32)
        at com.example.android.unscramble.ui.game.GameViewModel.<init>(GameViewModel.kt:23)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio 4.1.3
Build #AI-201.8743.12.41.7199119, built on March 11, 2021
Runtime version: 1.8.0_242-release-1644-b3-6222593 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 5.8.0-48-generic
_API version of the emulator:_ 
API 30
![Screenshot from 2021-04-23 15-05-59](https://user-images.githubusercontent.com/8808611/115855600-dd273e00-a444-11eb-8928-0d5f4e9e142e.png)

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by pranjal-codes** [comment]
Make sure to use the init{ } block after the variable declarations

**Comment by jtavva** [comment]
@mshoaib-murtaza 
Thank you for reaching out to us.
This issue is same as https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/issues/46
Refer to the above issue for solution.
Please follow steps in order.
