### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by zminnde** [google-developer-training/android-basics-kotlin-unscramble-app#53]
**URL of codelab**
[https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12](url)

**In which task and step of the codelab can this issue be found?**

    private fun getNextWord() {
        currentWord = allWordsList.random()
        val tempWord = currentWord.toCharArray()
        tempWord.shuffle()

        while (tempWord.toString().equals(currentWord, false)) {
            tempWord.shuffle()
        }
        if (wordsList.contains(currentWord)) {
            getNextWord()
        } else {
            _currentScrambledWord = String(tempWord)
            ++_currentWordCount
            wordsList.add(currentWord)
        }
    }

**Describe the problem**
In this part of the code:

`while (tempWord.toString().equals(currentWord, false)) {
            tempWord.shuffle()
        }`
`tempWord.toString()` does not represent char array to String correctly.
I suggest using either `String(tempWord)` or `tempWord.concatToString()`

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@zminnde 
Same as #42 
Please refer to the above issue for solution.
