### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by pgaurav10** [google-developer-training/android-basics-kotlin-unscramble-app#54]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
Task 9: Implement OnClickListener for submit button

**Describe the problem**
After implementing the task run the code and you will see screen getting updated with the new word but score and number of words doesn't get updated.

So we need to write code for that as well.  

**Steps to reproduce?**
1. After completing the assignment run the app.
2. Check the values on screen.
3. Values of score and word count doesn't change, it should change.

**Versions**
_Android Studio version:_ all
_API version of the emulator:_ all

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Before_Submit](https://user-images.githubusercontent.com/15765810/116546190-f2054500-a90e-11eb-84bb-da66ec722f68.PNG)
![After_Submit](https://user-images.githubusercontent.com/15765810/116546232-ffbaca80-a90e-11eb-87a7-a3f379d1ac13.PNG)

**Comment by pranjal-codes** [comment]
You can see the values are changing in the logcat.  
You can proceed to the next topic for now.

**Comment by pgaurav10** [comment]
Yes, got to learn how it is handled in the next code lab but it was not mentioned there so I thought it's a mistake, nothing else.

Sorry for inconvenience!

**Comment by jtavva** [comment]
@pgaurav10 
Thank you for reaching out to us.
Glad you continued to the next codelab.
