### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by pranjal-codes** [google-developer-training/android-basics-kotlin-unscramble-app#55]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata&authuser=1#3

**In which task and step of the codelab can this issue be found?**

Task 4, Step 3

**Describe the problem**

Step 3 is , Change the backing field **`currentWordCount`** type to **`LiveData<String>`**, because it is immutable. Android Studio will show some errors which you will fix in the next steps.

So, currentWordCount is written there , ( obviously this variable should be an Integer ) . It must be **`currentScrambledWord`**.

**Steps to reproduce?**
1. Go to... 
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@pranjal-codes 
Thank you so much for reporting this issue. This is fixed and will be published soon.
