### ISSUE TITLE
Typo in Codelab: Android Basics: LiveData

### ISSUE THREAD

**Issue by manuelsucco** [google-developer-training/android-basics-kotlin-unscramble-app#56]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
3. Change the backing field currentWordCount type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps.

**Describe the problem**
the above mentioned backing field "currentWordCount" should be "currentScrambledWord".

**Comment by jtavva** [comment]
@manuelsucco 
Thank you so much for reporting this issue. This is fixed and will be published soon.
