### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by cScocco** [google-developer-training/android-basics-kotlin-unscramble-app#59]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#9

**In which task and step of the codelab can this issue be found?**
Use LiveData with ViewModel - setp 10 Test Unscramble app with Talkback enabled - substep 7

**Describe the problem**
No scrambled words were displayed after the change in substep 7

I think getter was missing and I fixed it by adding "get()" in the instruction:
val currentScrambledWord: LiveData<Spannable> get()= Transformations.map(_currentScrambledWord) {

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@cScocco 
Thank you for reaching out to us.
`get()` in the above code snippet is optional. In both cases, the code behaves the same way.
