### ISSUE TITLE
Android Basics: ViewModel: Wrong log tag for GameViewModel

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-unscramble-app#62]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel

**In which task and step of the codelab can this issue be found?**
6. The lifecycle of a ViewModel

**Describe the problem**
This section asks us to add logs for `GameViewModel` and `GameFragment`. However, the part for `GameViewModel` is:
```
class GameViewModel : ViewModel() {
   init {
       Log.d("GameFragment", "GameViewModel created!")
   }
   ...
}
```
The log is written in `GameViewModel`, but the log tag is `GameFragment`, which is misleading. Please fix it. Thanks.

**Comment by jtavva** [comment]
@johnlinp 
Thank you for reaching out to us.
This is done on purpose to make it easy to filter the messages.
