### ISSUE TITLE
Android Basics: LiveData: typo "game_frament.xml"

### ISSUE THREAD

**Issue by johnlinp** [google-developer-training/android-basics-kotlin-unscramble-app#64]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata

**In which task and step of the codelab can this issue be found?**
7. Use LiveData with data binding

**Describe the problem**
There is a typo: `game_frament.xml`. It should have been `game_fragment.xml`.

**Comment by jtavva** [comment]
@johnlinp 
I think the Typo is in **8. Add data binding variables**, not in **7. Use LiveData with data binding**.
Thank you so much for reporting this issue. This is fixed and will be published soon.
