### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Stan-Balabushevich** [google-developer-training/android-basics-kotlin-unscramble-app#65]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#5

**In which task and step of the codelab can this issue be found?**
step 6 
The lifecycle of viewModel

**Describe the problem**
Block init in class GameViewModel: 
init {
        Log.d("GameFragment", "GameViewModel created!")
        getNextWord()
    }
Should go after initialization of words list:
private var wordsList = mutableListOf<String>()

Or we get error:
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference

**Steps to reproduce?**
App craches after step 6 with error:
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
  
**Versions**
_Android Studio version: 4.2
_API version of the emulator: phisical device Xiaomi Redmi 7A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment]
@Stan-Balabushevich 
Thank you for reaching out to us.
Issue is same as #39. 
Please refer #39 for the solution.
