### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by ps-noob** [google-developer-training/android-basics-kotlin-unscramble-app#68]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by ps-noob** [comment]
![image](https://user-images.githubusercontent.com/70065210/119489933-d9574600-bd79-11eb-8e3f-9e4f5061e447.png)

**Comment by jtavva** [comment]
@ps-noob 
Thank you so much for reporting this issue. This is fixed and will be published soon.
