### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by KKH-tw** [google-developer-training/android-basics-kotlin-unscramble-app#71]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata#7

**In which task and step of the codelab can this issue be found?**
The 1st step of the page.

**Describe the problem**
In the sentence, "In game_frament.xml, inside the <data> tag and a child tag called <variable>, declare a property called gameViewModel and of the type GameViewModel." it seems that "and a child tag" should be "add a child tag".

Although the sentence with the "and" is not wrong, the following step (step 2) uses "add another variable inside the <data> tag", indicating the "and" in the 1st step is likely a typo.

**Steps to reproduce?**
As stated above.

**Versions**
Not applicable.

**Additional information**
Nil.

**Comment by jtavva** [comment]
@KKH-tw 
Thank you so much for reporting this issue. This is fixed and will be published soon.
