### ISSUE TITLE
Android Basics: ViewModel - inappropriate function to convert CharArray to string

### ISSUE THREAD

**Issue by bivanbi** [google-developer-training/android-basics-kotlin-unscramble-app#72]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Task 6: "Sometimes the shuffled order of characters is the same as the original word. Add the following while loop around the call to shuffle, to continue the loop until the scrambled word is not the same as the original word."

**Describe the problem**
The example uses ```tempWord.toString()``` to get a String representation of the scrambled CharArray of letters to be comparable to the original word.

According to the [documentation](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-char-array/), CharArray does not have toString() method and as such returns the object identifier (memory address?) instead of the scambled letters converted to a string, which can be confirmed with logging.

This leads to condition ```tempWord.toString().equals(currentWord, false)``` always being evaluated to false, which in turn leads to word occasionally not being scrambled.

Replacing ```tempWord.toString()``` with ```String(tempWord)``` resolves this condition.

**Steps to reproduce?**
1. Implement private fun getNextWord() with _initial scrumbling intentionally omitted_ like this:
    ```
    private fun getNextWord() {
        currentWord = allWordsList.random()
        while(wordsList.contains(currentWord))
            getNextWord()

        val tempWord = currentWord.toCharArray()

        while (tempWord.toString().equals(currentWord, false)) {
            Log.d(TAG, "${object{}.javaClass.enclosingMethod?.name}: word: ${currentWord}: tempWord needs shuffle: ${String(tempWord)} (${tempWord.toString()}")
            tempWord.shuffle()
        }
        Log.d(TAG, "word: ${currentWord}: tempWord shuffled: ${String(tempWord)} (${tempWord.toString()})")
        Log.d(TAG, "word: ${currentWord}: tempWord.joinToString(): ${tempWord.joinToString(", ")}")
        Log.d(TAG, "word: ${currentWord}: tempWord.toString(): ${tempWord.joinToString(", ")}")
        Log.d(TAG, "word: ${currentWord}: String(tempWord): ${String(tempWord)}")
        (...)
   }
    ```
2. Run app
3. Observe word not scrambled, Logcat output:
    ```
    2021-05-30 09:04:57.195 12176-12176/com.example.android.unscramble D/GameFragment->ViewModel: word: visitor: tempWord shuffled: visitor ([C@3cd26fc)
    2021-05-30 09:04:57.208 12176-12176/com.example.android.unscramble D/GameFragment->ViewModel: word: visitor: tempWord.joinToString(): v, i, s, i, t, o, r
    2021-05-30 09:04:57.208 12176-12176/com.example.android.unscramble D/GameFragment->ViewModel: word: visitor: tempWord.toString(): v, i, s, i, t, o, r
    2021-05-30 09:04:57.208 12176-12176/com.example.android.unscramble D/GameFragment->ViewModel: word: visitor: String(tempWord): visitor
    ```
4. Replace ```tempWord.toString()``` with ```String(tempWord)``` and observe expected results:
   ```
    2021-05-30 09:11:52.059 12314-12314/com.example.android.unscramble D/GameFragment->ViewModel: getNextWord: word: introduce: tempWord needs shuffle: introduce ([C@3cd26fc
    2021-05-30 09:11:52.071 12314-12314/com.example.android.unscramble D/GameFragment->ViewModel: word: introduce: tempWord shuffled: erunctdio ([C@3cd26fc)
   ```

**Versions**
_Android Studio version:_ Android Studio 4.2
Build #AI-202.7660.26.42.7322048, built on April 29, 2021
Runtime version: 11.0.8+0-b944-P17168821 amd64 
_API version of the emulator:_ 30
_Kotlin version:_ 1.5.10

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/8977026/120095655-56424100-c127-11eb-8343-4046ec08318d.png)

**Comment by durini309** [comment]
Was going to report the same 👍🏾 . You can use `.joinToString("")` instead

**Comment by jtavva** [comment]
@bivanbi 
@durini309 
Same as #42 
Thank you for reaching out to us.
Yes this is a known issue, the correct code is as follows:

```
while (String(tempWord).equals(currentWord, false)) {
    tempWord.shuffle()
}
```

Thank you so much for reporting this issue. This is fixed and will be published soon.
