### ISSUE TITLE
Android Basics: ViewModel - trying to modify a read-only value in getNextWord

### ISSUE THREAD

**Issue by bivanbi** [google-developer-training/android-basics-kotlin-unscramble-app#74]
**URL of codelab**
[Step 7. Store data in ViewModel](https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6)

**In which task and step of the codelab can this issue be found?**
Task 7 step 7: "Add an if-else block to check if a word has been used already" 

**Describe the problem**
Code snippet in _step 7_:
```
if (wordsList.contains(currentWord)) {
    getNextWord()
} else {
    _currentScrambledWord = String(tempWord)
    ++currentWordCount
    wordsList.add(currentWord)
}
```

At this point in the codelab, ```currentWordCount``` should already be a ```val``` (read-only) and as such cannot be incremented.
The method should increment the ```_currentWordCount``` property:
```
    ++_currentWordCount
```

Either Task 7 should be corrected or _Task 5 Move view Populate ViewModel_ should be more explicit / corrected as to describe how class variables / values should look like.

**Steps to reproduce?**
1. Enter code as suggested by the codelab into Android Studio
2. Observe error: "Val cannot be reassigned"

**Additional information**
Complete context:
```
class GameViewModel : ViewModel() {
    (...)
    private var _currentWordCount = 0
    val currentWordCount get() = _currentWordCount

    private fun getNextWord() {
        (...)
        _currentScrambledWord = String(tempWord)
        ++currentWordCount
}
```

**Comment by bivanbi** [comment]
On second thought, I might have been _over-doing_ excercise in Task 5 and implemented backing property of ``` currentWordCount``` too soon.

**Comment by jtavva** [comment]
@bivanbi 
Thank you for reaching out to us.
Yes that could be the issue.
