### ISSUE TITLE
null pointer exception on wordsList

### ISSUE THREAD

**Issue by araoko** [google-developer-training/android-basics-kotlin-unscramble-app#75]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#5

i just completed **Lifecycle of a view model** task and decided to run my code only for the app to crash with error:

java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.contains(java.lang.Object)' on a null object reference
        at com.example.android.unscramble.ui.game.GameViewModel.getNextWord(GameViewModel.kt:34)
        at com.example.android.unscramble.ui.game.GameViewModel.<init>(GameViewModel.kt:10)
        .....

on debugging my code I discovered the wordlist a property of  GameViewModel is null
the property is declared and initialised as **private var wordsList: MutableList<String> = mutableListOf()**

i expect it to me an empty list and not null. all other properties (except the lateinit ones) has values

below is my viewModel Class

```
class GameViewModel : ViewModel() {

    init {
        Log.d("GameFragment", "GameViewModel created!")
        getNextWord()
    }
    private var wordsList: MutableList<String> = mutableListOf()
    private var score = 0
    private var currentWordCount = 0
    private lateinit var _currentScrambledWord: String
    val currentScrambledWord: String
        get() = _currentScrambledWord


    private lateinit var currentWord: String

    override fun onCleared() {
        super.onCleared()
        Log.d("GameFragment", "GameViewModel destroyed!")
    }

    private fun getNextWord() {
        currentWord = allWordsList.random()
        val tempWord = currentWord.toCharArray()
        tempWord.shuffle()
        while (tempWord.toString().equals(currentWord, false)) {
            tempWord.shuffle()
        }
        if (wordsList.contains(currentWord)) {
            getNextWord()
        } else {
            _currentScrambledWord = String(tempWord)
            ++currentWordCount
            wordsList.add(currentWord)
        }
    }

    /*
* Returns true if the current word count is less than MAX_NO_OF_WORDS.
* Updates the next word.
*/
    fun nextWord(): Boolean {
        return if (currentWordCount < MAX_NO_OF_WORDS) {
            getNextWord()
            true
        } else false
    }
}
```

**Versions**
_Android Studio version:_ 4.2.1
_API version of the emulator:_ 28

**Comment by hahmraro** [comment]
The init block is called before the variable wordList is declared. Move the declaration of wordList above the init block, or just move the init block below all the variables.

**Comment by araoko** [comment]
> The init block is called before the variable wordList is declared. Move the declaration of wordList above the init block, or just move the init block below all the variables.
> 
> ```
> class GameViewModel : ViewModel() {
> 
>     private var wordList: MutableList<String> = mutableListOf()
> 
>     init {
>         Log.d(TAG, "GameViewModel created!")
>         getNextWord()
>     }
> ```

Thanks, it worked!
i thought the primary constructor comes before the init function and its responsible for initialising all the none lateinit properties
