### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by M-Phuykong** [google-developer-training/android-basics-kotlin-unscramble-app#76]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12

**Describe the problem**
In "GameViewModel".
`private fun getNextWord(){
        currentWord = allWordsList.random()
        val tempWord = currentWord.toCharArray()
        tempWord.shuffle()
        while (tempWord.toString().equals(currentWord, false)){
            tempWord.shuffle()
        }
        if (wordsList.contains(currentWord)){
            getNextWord()
        } else{
            _currentScrambledWord = String(tempWord)
            ++_currentWordCount
            wordsList.add(currentWord)
        }
    }`

I believe you forgot to mentioned about changing "++currentWordCount" to "++_currentWordCount" after making it into a read only function.

**Comment by jtavva** [comment]
@M-Phuykong 
Thank you so much for reporting this issue.
In the following step, when you refractor, all the occurrences will be changed including the one you mentioned. 

![image](https://user-images.githubusercontent.com/24260141/121721018-a068e200-ca98-11eb-868a-9ed9be4636b1.png)
