### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by M-Phuykong** [google-developer-training/android-basics-kotlin-unscramble-app#77]
**URL of codelab**

https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#7

**Describe the problem**

There's a typo of "game_fragment.xml" at the top of Step 8: Add data binding variables

**Comment by jtavva** [comment]
@M-Phuykong 
Thank you so much for reporting this issue. This is fixed and will be published soon.
