### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by pearlyadav** [google-developer-training/android-basics-kotlin-unscramble-app#78]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
Task 4 - Step 3

**Describe the problem**
There's a typo in the Instruction, the Instruction says to update the **currentWordCount** variable but the code snippet shows that we need to update the **currentScrambledWord**

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/41968366/120895481-aeeb6f80-c63a-11eb-8807-95fc93feea67.png)

**Comment by jtavva** [comment]
@pearlyadav 
Thank you so much for reporting this issue. This is fixed and will be published soon.
