### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by MayaFB** [google-developer-training/android-basics-kotlin-unscramble-app#8]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=5&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D5%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
7) Populate ViewModel: function getNextWord()

**Describe the problem**
The tutorial proposes that to first shuffle tempWord and then enter the while loop to make shure the word is really shuffled. This made me aware that the comparison in the while loop is wrong, as tempWord.toString() will never equal currentWord. It has to be String(tempWord) and then the shuffling before the while loop can eliminated.
/*
* Updates currentWord and currentScrambledWord with the next word.
*/
private fun getNextWord() {
   currentWord = allWordsList.random()
   val tempWord = currentWord.toCharArray()
   tempWord.shuffle()

   while (tempWord.toString().equals(currentWord, false)) {
       tempWord.shuffle()
   }
   if (wordsList.contains(currentWord)) {
       getNextWord()
   } else {
       _currentScrambledWord = String(tempWord)
       ++currentWordCount
       wordsList.add(currentWord)
   }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by nicogramm** [comment]
#9 has some more details about this

**Comment by jtavva** [comment]
@nicogramm @MayaFB 
Thank you for bringing this issue to our attention.
Changed the `while` condition. 
PR: https://github.com/google-developer-training/android-basics-kotlin-unscramble-app/pull/11
