### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by ozhanhakan** [google-developer-training/android-basics-kotlin-unscramble-app#81]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**

Change the backing field currentWordCount type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps.

val currentScrambledWord: LiveData<String>
   get() = _currentScrambledWord

**Describe the problem**

"currentWordCount" is mentioned in the explanation sentence.
but
passing "currentScrambledWord" in solution code.

The explanation sentence is misleading. it should be fixed.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/32941617/121809721-972d7000-cc66-11eb-813b-5b0d6278abde.png)

**Comment by jtavva** [comment]
@ozhanhakan 
Thank you so much for reporting this issue. This is fixed and will be published soon.
