### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by kod4n** [google-developer-training/android-basics-kotlin-unscramble-app#83]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?authuser=2&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%3Fauthuser%3D2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Task 7: Populate ViewModel

**Describe the problem**
I believe the while loop condition will always return false and never re-shuffle.  The while condition should use `String(tempWord)` or `tempWord.joinToString("")` instead of `tempWord.toString()`, this will compare the string in the char arraay to the current word.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by brunomateus** [comment]
I found the same issue.

**Comment by kylelamse** [comment]
Same problem here.  `tempWord.toString()` will return something like `[C@952150f`, which does not equal the value of `currentWord`.  I updated my code to use `String(tempWord)` and it got expected results.

It's easy to reproduce this bug if you just take away this line from `com.example.android.unscramble.ui.game.GameViewModel#getNextWord`:
`val tempWord = currentWord.toCharArray()`

**Comment by android-dev-lxl** [comment]
Thank you for reporting, this issue is fixed.
