### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Steve-NTI** [google-developer-training/android-basics-kotlin-unscramble-app#84]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#4

**In which task and step of the codelab can this issue be found?**
Step 3 is...
"In GameFragment, delete the code inside the methods onSubmitWord() and onSkipWord(). You will implement these methods later. You should be able to compile the code now without errors."

**Describe the problem**
The code does have an error when compiling. Both onSubmitWord and onSkipWord methods are used in onViewCreate method as designated Click Listeners. These lines must be deleted of commented out once the two methods are deleted.
The lines in my code are 56 and 57.

**Comment by osuleymanova** [comment]
Hello @Steve-NTI,

Thank you for reaching out to us and sharing your concern. Please review the updated steps:

![Screenshot 2023-01-25 at 9 19 38 AM](https://user-images.githubusercontent.com/86437155/214635681-bba1d86a-52dd-4e7e-90fc-4eb8800748d5.png)
