### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by Anshumanj95** [google-developer-training/android-basics-kotlin-unscramble-app#87]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12

**In which task and step of the codelab can this issue be found?**
in this game score and word count is not change on submit or skip button click and gameViewModel log is occur only once when app start it is not update

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by PiyushSonawane1302** [comment]
Add this in updateNextWordOnScreen() Method  
``binding.score.text = getString(R.string.score, viewModel.score)``
``binding.wordCount.text = getString(R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS)``

**Comment by PiyushSonawane1302** [comment]
Update Your <b>updateNextWordOnScreen()</b> with the below code
```kotlin
  private fun updateNextWordOnScreen() {
        binding.score.text = getString(R.string.score, viewModel.score)
        binding.wordCount.text = getString(R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS )
        binding.textViewUnscrambledWord.text = viewModel.currentScrambledWord
    }
```
