### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by AlanaFiordalisi** [google-developer-training/android-basics-kotlin-unscramble-app#88]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#0

**In which task and step of the codelab can this issue be found?**
Task 4 (Add LiveData to the current scrambled word)
Step 3

**Describe the problem**
Step 3 reads: "Change the backing field `currentWordCount` type to `LiveData<String>`...". However, the code snippet with the correct solution, shown immediately after this instruction, shows us updating `currentScrambledWord` (not `currentWordCount`). 

Based on the rest of the tasks, and the fact that `currentWordCount` should be an Int rather than a String altogether, I believe the code snippet is accurate but the description in the step has the wrong variable name

**Steps to reproduce?**
N/A

**Versions**
_Android Studio version:_ N/A
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="776" alt="Task4_Step3" src="https://user-images.githubusercontent.com/33777378/123448965-3af11700-d5a9-11eb-8e8c-b2fa28e14012.png">

**Comment by osuleymanova** [comment]
@AlanaFiordalisi 
Thank you for reaching out to us. The issue was fixed.
