### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by TheReformedAlloy** [google-developer-training/android-basics-kotlin-unscramble-app#89]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
Task 4, Step 3

**Describe the problem**
The text reads to change the type of the backing field currentWordCount, but the example and surrounding context imply it should be currentScrambledWord.

**Steps to reproduce?**
1. Go to Codelab
2. Go to task 4
3. Read step 3

**Versions**
_Android Studio version:_ 4.13
_API version of the emulator:_ N/A

**Additional information**

**Comment by osuleymanova** [comment]
@TheReformedAlloy 
Thank you for reaching out to us. The issue was fixed.
