### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by GregBradb** [google-developer-training/android-basics-kotlin-unscramble-app#9]
Store data in ViewModel

**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#6

**In which task and step of the codelab can this issue be found?**
Task 7:  Populate ViewModel
Step 6

**Describe the problem**
In step 6 we add:
   while (tempWord.toString().equals(currentWord, false)) {
       tempWord.shuffle()
   }
This is intended to capture any case where the shuffled word results in no change in character order.  In fact, the "tempWord.toString()" returns something that looks somewhat like the hex representation of a memory address, not the content of the tempWord CharArray.  This block of code will NEVER execute and it will not catch the case where the shuffled word is the same as the current word.

I suspect what you wanted to do was to use:  "while (String(tempWord).equals(currentWord, false)) {"

**Steps to reproduce?**
1. Go to...  Follow all steps of the "Store data in ViewModel" instructions.  Add 
   Log.d("Game Fragment",  "tempWord:  ${tempWord.toString()}")
before the while statement (see first screen capture below).
Run the program and review the output of the debug Log outputs to see what is printed at this location.
2. Click on...
3. See error...

**Versions**
_Android Studio version:_  4.1.1
_API version of the emulator:_  29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
Add Log.d to the code:
![image](https://user-images.githubusercontent.com/8106705/104652844-90c2aa00-566e-11eb-83a0-989dfbf2da89.png)

Debug output:
![image](https://user-images.githubusercontent.com/8106705/104653297-3ece5400-566f-11eb-9c4c-b4c11509226f.png)

**Comment by nicogramm** [comment]
Some trivia about this:
https://discuss.kotlinlang.org/t/array-tostring-vs-list-tostring/2244/

**Comment by jtavva** [comment]
@nicogramm 
Thank you for bringing this issue to our attention.
Changed the `while` condition.
PR: #11
