### ISSUE TITLE
Android Basics: ViewModel

### ISSUE THREAD

**Issue by zheng-zhao** [google-developer-training/android-basics-kotlin-unscramble-app#92]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-viewmodel?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-viewmodel#12

**In which task and step of the codelab can this issue be found?**
Store data in ViewModel
Solution code

**Describe the problem**
GameFragment.kt
private fun updateNextWordOnScreen()
We need to add the following 2 rows to update the score and current word account together with the current word.
binding.wordCount.text = getString(R.string.word_count, viewModel.currentWordCount, MAX_NO_OF_WORDS)
binding.score.text = getString(R.string.score, viewModel.score)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by worifsaim** [comment]
Thank you for this code. It helped me fix my app since I encountered exactly that problem of scores' visual representation not updating.
