### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by JasminKir** [google-developer-training/android-basics-kotlin-unscramble-app#93]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3 

**In which task and step of the codelab can this issue be found?**
Task 4: Add LiveData to the current scrambled word
Step 3 "Change the backing field currentWordCount type to LiveData<String>, because it is immutable. Android Studio will show some errors which you will fix in the next steps."

**Describe the problem**
"currentWordCount" is wrong. Instead, the backing field type of "currentScrambledWord" needs to be changed to "LiveData<String".

**Additional information**
![image](https://user-images.githubusercontent.com/18593808/124508319-fc8d0080-ddcf-11eb-9282-a1fb42798af6.png)

**Comment by JasminKir** [comment]
Found duplicates of the issue here: #89 and #88

**Comment by osuleymanova** [comment]
@JasminKir 
Thank you for reporting this issue. It was fixed and republished.
