### ISSUE TITLE
Android Basics: LiveData

### ISSUE THREAD

**Issue by ApunichGULSHER** [google-developer-training/android-basics-kotlin-unscramble-app#98]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-livedata?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-3%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-livedata#3

**In which task and step of the codelab can this issue be found?**
Task 4, step 3

**Describe the problem**
you write currentWordCount instead of currentScrambledWord.
you write it correct in code below the task

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@ApunichGULSHER 
Thank you for reaching out to us.
This should be fixed now.
